### ISSUE TITLE
Instance types not found in different AWS region

### ISSUE THREAD

**Issue by grdnrio** [PureStorage-OpenConnect/px-deploy#12]
When deploying in a different region, the default instance type is missing causing errors. Can a check be added to make sure the instance type is available with a more graceful failure if it is missing. Alternatively we could add a default instance for each region.

**Comment by andrewh1978** [comment]
fixed in https://github.com/andrewh1978/px-deploy/commit/43f94a1663e6f4a038400915650a3008a0ace8d1
