### ISSUE TITLE
Download kubeconfig file to local machine

### ISSUE THREAD

**Issue by grdnrio** [PureStorage-OpenConnect/px-deploy#127]
It would be helpful to automatically create a merged config file for multiple clusters and download this onto a local machine setting the env var in the process. Some customers question ssh-ing to a master to demo from.

**Comment by bplein** [comment]
Bravo! I've been a big fan of demoing K8s from a local machine. Want a sexy shell prompt? Check. Want a few other tools at your disposal? Check. Want to avoid the "No SSH" issue raised above? Check!

**Comment by andrewh1978** [comment]
I can certainly add this, but you can do this today and achieve the same thing:

`px-deploy connect -n foo cat /root/.kube/config >$KUBECONFIG`

Is that adequate?

**Comment by grdnrio** [comment]
I tried this but it uses the private IP of the nose. I think we need to change the kubernetes install parameters to listen on the instance public IP.

Joe
