### ISSUE TITLE
Add a reaper or deployment timeout setting to reduce costs

### ISSUE THREAD

**Issue by grdnrio** [PureStorage-OpenConnect/px-deploy#14]

**Comment by aleks-mariusz** [comment]
usually you would post which PR it is that fixes the issue.. all that's visible here is 'no description provided' which is not very helpful in case someone wants to cross-reference how this was implemented :-(

**Comment by andrewh1978** [comment]
https://github.com/andrewh1978/px-deploy/commit/b92f2b29573b33aba058c26bb9bc12caca896e0f
