### ISSUE TITLE
px-deploy should fail with an error is EKS deployment script fails

### ISSUE THREAD

**Issue by rdeenik** [PureStorage-OpenConnect/px-deploy#168]
When you try to deploy an EKS cluster on AWS, and the creating of the cluster fails (eg. because the maximum allowed number of VPC's is reached in AWS), the deployment continues without any error. Ideally px-deploy would fail, possibly showing the `eksctl` error output.

This issue related to the `eks-master` script in the vagrant directory, specifically line 15:
```eksctl create cluster --region $aws_region --nodes $nodes --node-type $aws_type --name $EKS_CLUSTER_NAME```

**Comment by andrewh1978** [comment]
We will fix this when we move to Terraform
