### ISSUE TITLE
RFE: Specify GCP project instead of creating a new one

### ISSUE THREAD

**Issue by bplein** [PureStorage-OpenConnect/px-deploy#180]
Today `px-deploy` creates a new GCP project and installs into it. It also destroys that project when `px-deploy destroy` is called. I'd like to be able to specify the project that it deploys into, and not destroy that project. Specific use case is that I only have access to one project through work, and cannot us px-deploy with that project.

**Comment by danpaul81** [comment]
done in GCP terraform re-work

**Comment by danpaul81** [comment]
done in GCP terraform re-work

**Comment by bplein** [comment]
I don't even remember creating this issue. When I read it, it's as if someone else wrote it (grin).
