### ISSUE TITLE
kubernetes yum repo breaks yum

### ISSUE THREAD

**Issue by bplein** [PureStorage-OpenConnect/px-deploy#212]
The repo /etc/yum.repos.d/kubernetes.repo breaks yum commands. 

Workaround is to use yum --disable-repo kubernetes, but I'd also like to remove it. But the VM doesn't have yum-utils installed.

**Comment by davidcastellani** [comment]
@bplein is this issue resolved for you?

**Comment by bplein** [comment]
I switched to using `dnf` for my package manager needs in VMs deployed with `px-deploy`
