### ISSUE TITLE
Clean up old image signatures

### ISSUE THREAD

**Issue by bplein** [PureStorage-OpenConnect/px-deploy#340]
Today we are only keeping `:dev` and `:${VERSION}` tags.   But every `dev` build will leave a new `.sig` file as we are using signed images. Since each `.sig` is uniquely named, these are not going to go away when a new `dev` image is built.

We could just abandon signing images, which is the easy way to  avoid this litter. The second way is for us to figure out if we can clean up old versions in the action workflow itself, OR apply a retention period. There is documentation on artifact retention but these builds are not considered artifacts (our builds show zero artifacts). 

I'll assign this to myself. Using this issue to track.

**Comment by bplein** [comment]
@andrewh1978 @danpaul81 Do you see any reason to keep signatures? If not, I'll test turning them off on my fork and then submit a PR.

**Comment by andrewh1978** [comment]
I would turn them off.

**Comment by bplein** [comment]
Fixed by PR. Closing (I will manually remove old .sig files from the packages area)
