### ISSUE TITLE
Port to AWS/GCP SDKs

### ISSUE THREAD

**Issue by andrewh1978** [PureStorage-OpenConnect/px-deploy#4]
px-deploy uses the AWS and GCP CLI to manage infrastructure; we should move to the SDKs

**Comment by aleks-mariusz** [comment]
in an ideal world with infinite time, i'd agree.. but in the real world for what benefit would we want to go through the level of effort to make this change? 

example - i think some of the go-code is pretty ugly formatting-wise, but i'm not masochistic enough to want to re-write it if it works as it is now :-)

**Comment by canadianchris** [comment]
The real world benefit would be getting closer to a single multi-platform binary with some concurrency optimizations. but, we all have day jobs :)
