### ISSUE TITLE
cannot specify multiple ebs disks

### ISSUE THREAD

**Issue by andrewh1978** [PureStorage-OpenConnect/px-deploy#433]
[root@px-deploy ~]# px-deploy create -n test --aws_ebs "gp2:50 gp2:50"
Current version is 5.2 (latest)
Invalid arguments

**Comment by danpaul81** [comment]
seems to be a bash (4.4.20) related issue. space within the aws_ebs parameter seems to be wrongly interpreted. works with bash 5 & zsh
