### ISSUE TITLE
Joe and Andrew - WIP tasks

### ISSUE THREAD

**Issue by grdnrio** [PureStorage-OpenConnect/px-deploy#69]
- [ ] add kubectl patch to metro
- [x] move storkctl install to px-install (and any other scripts that install px, eg cp4d)
- [x] move aws stuff out of async-dr
- [x] move aws stuff out of metro
- [x] separate licence script
- [x] dont apply async dr to remote clusters

**Comment by aleks-mariusz** [comment]
ignore my edits above, was just playing around with your use of checkboxes :-)
