### ISSUE TITLE
PWX CSI: support install of PX with CSI

### ISSUE THREAD

**Issue by wallnerryan** [PureStorage-OpenConnect/px-deploy#79]
right now I think we dont do this by default which is fine, but i dont think there is a knob?

**Comment by andrewh1978** [comment]
You could do:
`px-deploy -n foo -t px -e px_suffix=csi%3Dtrue`
Will that work for you?

**Comment by wallnerryan** [comment]
Ah, yeah this is fine, didnt realize this was an option or missed if was spelled out somewhere.
